# Site settings
name: Kelvin Kamau
title: Kelvin Kamau | Software Developer
description: Detail oriented software engineer passionate about combining beautiful code with beautiful design.
url: https://www.kelvinkamau.app
baseurl: ""
email: chat@kelvinkamau.app
cover: https://www.kelvinkamau.app/og.png
logo: https://www.kelvinkamau.app/img/icon.png
resume: https://www.kelvinkamau.app
social:
  - title: twitter
    url: https://twitter.com/kamaucodes
  - title: instagram
    url: https://instagram.com/justkeykay
  - title: github
    url: https://github.com/kelvinkamau
  - title: linkedin
    url: https://www.linkedin.com/in/kelvinkamau
  - title: privacypolicy
    url: https://www.kelvinkamau.app/PrivacyPolicy/

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
